name: Teste Continuo (CI)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  verificacao-codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o codigo
      uses: actions/checkout@v3

    - name: Configurando o PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Verificando erros de sintaxe no PHP
      run: find . -name "*.php" -print0 | xargs -0 -n1 php -l